# Generated by Django 2.0.6 on 2018-06-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(db_column='id', max_length=12, primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, db_column='user', max_length=32)),
                ('pwd', models.CharField(blank=True, db_column='password', max_length=32)),
            ],
            options={
                'db_table': 'user_test',
            },
        ),
    ]
