# Generated by Django 2.0.6 on 2018-06-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysqltest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='user_test',
        ),
    ]
