# Generated by Django 2.0.6 on 2018-06-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqltest', '0002_auto_20180629_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charactor',
            fields=[
                ('cid', models.AutoField(db_column='CID', max_length=11, primary_key=True, serialize=False)),
                ('charactor', models.CharField(db_column='charactor', max_length=255)),
                ('hGroup', models.IntegerField(db_column='h_group', max_length=11)),
            ],
            options={
                'db_table': 'user_charactor',
            },
        ),
    ]
