# Generated by Django 2.0.6 on 2018-06-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqltest', '0003_charactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(db_column='主键id', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(blank=True, db_column='密码', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.CharField(blank=True, db_column='用户名', max_length=32),
        ),
    ]
