# Generated by Django 2.0.6 on 2018-06-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqltest', '0004_auto_20180629_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(db_column='id', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(blank=True, db_column='password', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.CharField(blank=True, db_column='user', max_length=32),
        ),
    ]
